### ISSUE TITLE
Parameterized cycling

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/ice-floe-tracker-pipeline#68]
Ideally run a Cylc flow file for each set of parameters. 

One option is to cycle through set of params within Cylc, another is to use an array job directly on Oscar/slurm. 

Can parameters be passed from an array batch job script to the Cylc flow script?

**Comment by tdivoll** [comment]
Cylc - platform = slurm
Seems like we can use the SBATCH directives in Cylc: 
https://cylc.github.io/cylc-doc/latest/html/user-guide/task-implementation/job-runner-handlers/cylc.flow.job_runner_handlers.slurm.html#module-cylc.flow.job_runner_handlers.slurm[](https://cylc.github.io/cylc-doc/latest/html/user-guide/task-implementation/job-runner-handlers/cylc.flow.job_runner_handlers.slurm.html#module-cylc.flow.job_runner_handlers.slurm)

**Comment by cpaniaguam** [comment]
@tdivoll After exploring Cylc [Parametrized Tasks](https://cylc.github.io/cylc-doc/stable/html/user-guide/writing-workflows/parameterized-tasks.html#task-parameters), it seems like templating is likely the most viable solution for this use case. Below is a possible initial implementation.

- Here are some sample files to start with. A template file and a data file with which to fill the template are needed.
```yaml
# cycl template mytemplate.j2
[runtime]
    [[root]]
        [[[environment]]]
            # Update these variables with your run parameters
            startdate = {{startdate}}
            enddate = {{enddate}}
            crs = "wgs84" #epsg3413 for polar stereographic
            bounding_box = {{bounding_box}}
            centroid_x = {{centroid_x}}
            centroid_y = {{centroid_y}}
            minfloearea = {{minfloearea}}
            maxfloearea = {{maxfloearea}}
            project_dir = "~/ice-floe-tracker-pipeline"

```
```yaml
# sample-env.yaml
startdate: 
   - "2015-01-01"
   - "2015-02-01"
   - "2015-03-01"
enddate:
   - "2015-01-31"
   - "2015-02-28"
   - "2015-03-31"
bounding_box: 
   - "78.186394 38.250605 70.749318 15.32373"
   - "78.186394 38.250605 70.749318 15.32373"
   - "78.186394 38.250605 70.749318 15.32373"
centroid_x: 
   - "75"
   - "76"
   - "77"
centroid_y: 
   - "21"
   - "22"
   - "23"
minfloearea: 
   - "300"
   - "400"
   - "500"
maxfloearea: 
   - "90000"
   - "90001"
   - "90002"
```
- Python code to generate the cycl files from the template and env file
```python
from jinja2 import Environment, FileSystemLoader # templating engine
import yaml # parser

def parse_paramsyml(yamlfile):
    """
    Parse yaml file with parameters for cylc files.    
    """
    with open(yamlfile, "r") as f:
        dataimp = yaml.load(f, Loader=yaml.FullLoader)
    n = len(dataimp["startdate"])
    return [{k: dataimp[k][i] for k in dataimp} for i in range(n)]

def generate_cylc_files(envfile, template, template_dir="."):
    """
    Generate cylc files from template.

    Parameters
    ----------
    envfile : str
        Path to yaml file with parameters for cylc files.
    template : str
        Name of template file.
    template_dir : str
        Path to directory with template file.
    """
    data = parse_paramsyml(envfile)
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template(template)
    for i, conf in enumerate(data, 1):
        fname = "flow" + str(i) + ".cylc"
        content = template.render(conf)
        with open(fname, "w") as fh:
            fh.write(content)
```
When running `generate_cylc_files("sample-env.yaml", "mytemplate.j2")` three files are generated (`flow1.cylc`, ..., `flow3.cylc`)
```yaml
# flow1.cylc
[runtime]
    [[root]]
        [[[environment]]]
            # Update these variables with your run parameters
            startdate = 2015-01-01
            enddate = 2015-01-31
            crs = "wgs84" #epsg3413 for polar stereographic
            bounding_box = 78.186394 38.250605 70.749318 15.32373
            centroid_x = 75
            centroid_y = 21
            minfloearea = 300
            maxfloearea = 90000
            project_dir = "~/ice-floe-tracker-pipeline"
```
Note that the first set of values were in `sample-env.yaml` were filled into the template. Then on Oscar one could do a job array with the generated `cylc` files. Thoughts? @mirestrepo
